import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextUiProvider from './NextUiProvider'
import Header from './components/Header'
import 'react-toastify/dist/ReactToastify.css';
import Footer from './components/Footer'
import { ToastContainer } from 'react-toastify'
import { AuthProvider } from './context/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUiProvider>
          <AuthProvider>
            <Header />
            <div className='text-white'>
              {children}
            </div>
            <Footer />
          </AuthProvider>
          <ToastContainer />
        </NextUiProvider>
      </body>

    </html>
  )
}
